[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "openapi-preview"
version = "0.2.1"
description = "A local preview server for OpenAPI YAML files"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["swagger-ui-bundle>=1.1,<2"]

[project.scripts]
openapi = "openapi_preview.cli:main"

[dependency-groups]
dev = ["mypy>=1.15", "pre-commit>=4.2", "pytest>=8", "ruff>=0.11"]

[tool.hatch.build.targets.wheel]
packages = ["src/openapi_preview"]

[tool.mypy]
strict = true

# Swagger bundle is a third-party package that does not have type hints
# and is basically all javascript, so we need to ignore missing imports for it.
[[tool.mypy.overrides]] 
module = ["swagger_ui_bundle"]
ignore_missing_imports = true
